name: Deploy to S3
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME : "nick-quigley.com"
  AWS_REGION : "us-east-2"
permissions:
  id-token: write
  contents: read 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::540375408222:role/CodePipeline
          role-session-name: s3syncer
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://nick-quigley.com
